import React, { useMemo } from "react";
import { Dialog, Transition } from "@headlessui/react";
import { PrinterIcon } from "@heroicons/react/24/outline";
import { useStandardMastery } from "../context/StandardMasteryContext";
import { useProfile } from "../context/ProfileContext";
import useStandardsData from "../hooks/useStandardsData";

interface ReportModalProps {
  isOpen: boolean;
  closeModal: () => void;
}

interface ReportRow {
  subject: string;
  grade: string;
  standardId: string;
  description: string;
  status: "completed" | "needs_improvement";
  updatedAt: string | null;
}

function formatMonthYear(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", { month: "long", year: "numeric" });
}

const STATUS_LABEL: Record<string, string> = {
  completed: "✓ Completed",
  needs_improvement: "~ Needs Work",
};

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function buildPrintHtml(
  groups: Array<{ label: string; items: ReportRow[] }>,
  profileName: string,
  generatedDate: string
): string {
  const groupsHtml = groups
    .map(
      (group) => `
      <div class="month">${escapeHtml(group.label)}</div>
      <table>
        <thead>
          <tr>
            <th class="id-col">ID</th>
            <th>Description</th>
            <th class="status-col">Status</th>
          </tr>
        </thead>
        <tbody>
          ${group.items
            .map(
              (row) => `
            <tr>
              <td class="id-col mono">${escapeHtml(row.standardId)}</td>
              <td>
                <span class="subject-label">${escapeHtml(row.subject)} · Gr.${escapeHtml(row.grade)}</span>
                ${escapeHtml(row.description)}
              </td>
              <td class="status-col">
                <span class="${row.status === "completed" ? "badge-completed" : "badge-needs"}">
                  ${row.status === "completed" ? "&#10003; Completed" : "~ Needs Work"}
                </span>
              </td>
            </tr>`
            )
            .join("")}
        </tbody>
      </table>`
    )
    .join("");

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Progress Report — ${escapeHtml(profileName)}</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; margin: 1in; color: #111; }
    h1 { font-size: 1.2rem; margin: 0 0 0.2rem; }
    .meta { font-size: 0.75rem; color: #666; margin-bottom: 1.5rem; }
    .month { font-size: 0.85rem; font-weight: 600; background: #f3f4f6;
             padding: 3px 10px; border-radius: 4px; margin: 1.25rem 0 0.4rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.8rem; margin-bottom: 0.5rem; }
    th { text-align: left; color: #666; font-weight: 500;
         border-bottom: 1px solid #d1d5db; padding: 2px 6px 4px 0; }
    td { padding: 4px 6px 4px 0; vertical-align: top;
         border-bottom: 1px solid #f3f4f6; }
    .id-col { width: 7.5rem; }
    .mono { font-family: monospace; color: #6b7280; font-size: 0.75rem; }
    .subject-label { display: block; font-size: 0.7rem; color: #4f46e5; margin-bottom: 1px; }
    .status-col { width: 8rem; text-align: right; white-space: nowrap; }
    .badge-completed { background: #d1fae5; color: #065f46;
                       padding: 1px 6px; border-radius: 3px; font-size: 0.75rem; }
    .badge-needs { background: #fef3c7; color: #92400e;
                   padding: 1px 6px; border-radius: 3px; font-size: 0.75rem; }
    footer { margin-top: 2rem; padding-top: 0.5rem; border-top: 1px solid #e5e7eb;
             font-size: 0.65rem; color: #9ca3af; }
  </style>
</head>
<body>
  <h1>Progress Report — ${escapeHtml(profileName)}</h1>
  <div class="meta">Generated ${escapeHtml(generatedDate)}</div>
  ${groupsHtml}
  <footer>Generated by V-SOL Explorer &middot; https://clates.github.io/v-sol-explorer</footer>
  <script>window.onload = function() { window.print(); window.close(); };</scr` + `ipt>
</body>
</html>`;
}

const ReportModal: React.FC<ReportModalProps> = ({ isOpen, closeModal }) => {
  const { getMasteryEntry, getProfiles } = useStandardMastery();
  const { selectedProfileId } = useProfile();
  const { standardsData } = useStandardsData({ useCache: true });

  const profile = getProfiles().find((p) => p.id === selectedProfileId);

  const rows = useMemo<ReportRow[]>(() => {
    if (!standardsData.length) return [];
    const result: ReportRow[] = [];
    for (const subjectStandard of standardsData) {
      for (const category of subjectStandard.categories) {
        for (const standard of category.standards) {
          const entry = getMasteryEntry(subjectStandard.subject, standard.id);
          if (entry.status === "not_started") continue;
          result.push({
            subject: subjectStandard.subject,
            grade: subjectStandard.grade,
            standardId: standard.id,
            description: standard.description,
            status: entry.status as "completed" | "needs_improvement",
            updatedAt: entry.updatedAt,
          });
        }
      }
    }
    return result;
  }, [standardsData, getMasteryEntry]);

  const groups = useMemo(() => {
    const buckets = new Map<string, ReportRow[]>();
    for (const row of rows) {
      const key = row.updatedAt
        ? formatMonthYear(row.updatedAt)
        : "__unknown__";
      if (!buckets.has(key)) buckets.set(key, []);
      buckets.get(key)!.push(row);
    }

    // Sort chronologically; "Date Unknown" last
    const sorted = Array.from(buckets.entries()).sort(([a], [b]) => {
      if (a === "__unknown__") return 1;
      if (b === "__unknown__") return -1;
      return new Date(a).getTime() - new Date(b).getTime();
    });

    return sorted.map(([key, items]) => ({
      label: key === "__unknown__" ? "Date Unknown" : key,
      items,
    }));
  }, [rows]);

  const generatedDate = useMemo(
    () =>
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
    []
  );

  return (
    <Transition.Root show={isOpen} as={React.Fragment}>
      <Dialog as="div" className="relative z-10" onClose={closeModal}>
        <Transition.Child
          as={React.Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
        </Transition.Child>

        <div className="fixed inset-0 z-10 overflow-y-auto">
          <div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <Transition.Child
              as={React.Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
              enterTo="opacity-100 translate-y-0 sm:scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 translate-y-0 sm:scale-100"
              leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            >
              <Dialog.Panel className="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-2xl">
                <div className="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                  <div className="mb-4">
                    <Dialog.Title
                      as="h3"
                      className="text-lg font-semibold leading-6 text-gray-900"
                    >
                      Progress Report —{" "}
                      {profile?.displayName ?? "Student"}
                    </Dialog.Title>
                    <p className="text-xs text-gray-500 mt-0.5">
                      Generated {generatedDate}
                    </p>
                  </div>

                  {rows.length === 0 ? (
                    <div className="text-center py-10 text-gray-500 text-sm">
                      No standards have been marked yet. Start tracking progress
                      to generate a report.
                    </div>
                  ) : (
                    <div className="max-h-[60vh] overflow-y-auto space-y-6 pr-1">
                      {groups.map((group) => (
                        <div key={group.label}>
                          <h4 className="text-sm font-semibold text-gray-700 bg-gray-100 px-3 py-1 rounded mb-2">
                            {group.label}
                          </h4>
                          <table className="w-full text-sm border-collapse">
                            <thead>
                              <tr className="text-left text-xs text-gray-500 border-b border-gray-200">
                                <th className="pb-1 pr-2 w-24">ID</th>
                                <th className="pb-1 pr-2">Description</th>
                                <th className="pb-1 w-28 text-right">
                                  Status
                                </th>
                              </tr>
                            </thead>
                            <tbody>
                              {group.items.map((row) => (
                                <tr
                                  key={`${row.subject}-${row.standardId}`}
                                  className="border-b border-gray-100 last:border-0"
                                >
                                  <td className="py-1.5 pr-2 font-mono text-xs text-gray-500 align-top">
                                    {row.standardId}
                                  </td>
                                  <td className="py-1.5 pr-2 text-gray-800 align-top">
                                    <span className="text-xs text-indigo-600 mr-1">
                                      {row.subject} · Gr.{row.grade}
                                    </span>
                                    {row.description}
                                  </td>
                                  <td className="py-1.5 text-right align-top whitespace-nowrap">
                                    <span
                                      className={`inline-block px-1.5 py-0.5 rounded text-xs font-medium ${
                                        row.status === "completed"
                                          ? "bg-emerald-100 text-emerald-800"
                                          : "bg-amber-100 text-amber-800"
                                      }`}
                                    >
                                      {STATUS_LABEL[row.status]}
                                    </span>
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6 gap-2">
                  <button
                    type="button"
                    className="inline-flex w-full justify-center items-center rounded-md bg-blue-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-blue-500 sm:ml-3 sm:w-auto cursor-pointer"
                    onClick={() => {
                      const printWindow = window.open("", "_blank");
                      if (!printWindow) return;
                      printWindow.document.write(
                        buildPrintHtml(
                          groups,
                          profile?.displayName ?? "Student",
                          generatedDate
                        )
                      );
                      printWindow.document.close();
                    }}
                  >
                    <PrinterIcon className="h-4 w-4 mr-1.5" />
                    Print
                  </button>
                  <button
                    type="button"
                    className="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto cursor-pointer"
                    onClick={closeModal}
                  >
                    Close
                  </button>
                </div>
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition.Root>
  );
};

export default ReportModal;
